### ISSUE TITLE
Feat: 편지 상세 조회 페이지 제작

### ISSUE THREAD

**Issue by cdm1263** [AIGOO-Epson/frontend#2]
## Issue 설명
- 편지 상세 보기 페이지 제작

## Todo
- [x]  문장별 키워드 선택 페이지 제작
- [x]  키워드 선택 및 서버로 저장 기능 구현
- [x]  선택된 키워드 강조 표시
- [ ]  원본 이미지 확인 기능 구현
